### ISSUE TITLE
Horizontal DraxList items vanish while shifting on Android

### ISSUE THREAD

**Issue by lafiosca** [nuclearpasta/react-native-drax#1]
With a DraxList in horizontal mode, on Android the items seem to vanish while they are shifted during a reordering drag. This does not happen on iOS, and it does not happen in vertical mode. It appears that Android may be doing some kind of additional view clipping on each view inside the underlying FlatList to cause this. Without digging into React Native's code, it's unclear why this would only apply to horizontal mode. It's also not obvious to me whether there could be a simple solution or workaround that we can apply within in this library.

Minimal reproduction example here: https://snack.expo.io/@lafiosca/horizontal-draxlist?platform=android

**Comment by lafiosca** [comment]
The existing shift system applies transforms to all the items in the list that need to be adjusted. Brainstorming, here are two potential alternative approaches if we can't make the existing approach work:

1) Actually reduce the size of the shifted item in the list to 0 and insert an additional item in the list wherever the dragged item is hovering. I think this might end up looking much jerkier than the smooth animations we have now because of views being destroyed/recreated, but I'm not sure without testing.

2) Only when on Android and in horizontal mode, render a whole bunch of additional hover copies of the views. This seems like overkill and might have an extreme performance impact, but we already know that hover views as implemented by Drax do not get clipped in this way. I do not want to have to use this approach.

**Comment by DmitriyNikolenko** [comment]
Any updates or solutions about how to resolve this issue?

**Comment by lafiosca** [comment]
I apologize, @DmitriyNikolenko, but I haven't had availability to focus on fixing this use case. The speculation above is all the progress that was made. I do not know when I will be able to research it more deeply, but anyone is welcome to explore it in the meantime and share their findings.

**Comment by DmitriyNikolenko** [comment]
I am sure this bug appears due to using FlatList in DraxList component. If we change FlatList to ScrollView this bug will be fixed.

**Comment by lafiosca** [comment]
@DmitriyNikolenko If we switched from `FlatList` to `ScrollView`, wouldn't we (in theory) lose the virtualized list item benefits for long lists though?

**Comment by lafiosca** [comment]
While working on other items, I just noticed that this behavior no longer occurs with the latest versions of libraries I'm using. I am not sure when this changed. I am using react-native 0.63.3 and react-native-drax 0.7.2 and have tested on a Pixel 2 emulator running Android 8.1 as well as a physical Nokia 3.4 phone running Android 10. If anyone still runs into this issue, feel free to comment here with information about your device and versions. For now I will close the issue.
