### ISSUE TITLE
DraxList items doesn't rendered

### ISSUE THREAD

**Issue by ApWin** [nuclearpasta/react-native-drax#105]
I was give array to DraxList's data and it works properly, Drag and Drop also works fine. 
The problem is  when I deleted one of them (it deleted from array), screen Page rendered but renderItemContent doesn't rendered and showed deleted item. 

**What can I do in that case ?**

**Comment by lafiosca** [comment]
I’m a little unclear on exactly what you’re describing. Is your last line saying that the deleted item is still being rendered? Or are you saying that none of the other items are being rendered?

It would be very helpful if you could provide a minimal reproduction of the bad behavior in Snack.

**Comment by ApWin** [comment]
Thanks for your attention @lafiosca . I don't have a permission to do this Snack. 

Yeah, deleted item is still rendered, appeared on the list but it erased from array. (I checked this by console )

**Comment by lafiosca** [comment]
It looks like the problem may be in your delete logic. You are splicing `selectedImages` directly rather than updating the array via `setState`.

**Comment by ApWin** [comment]
@lafiosca  Thanks, Bro )
