### ISSUE TITLE
Hover on absolute elements

### ISSUE THREAD

**Issue by tommyy911** [nuclearpasta/react-native-drax#114]
Hi, I've a problem with hovering ( calculating positions ) when elements are zoomed in.
I have a board with a lot of elements and there is a possibility to zoom in\out and move the board in any direction.
And I have a section with draggable elements ( on this board ).  I've noticed that when I'm zooming, the hover position is wrong. 

(2 pics for better explanation)
<img width="574" alt="Zrzut ekranu 2021-09-26 o 15 57 40" src="https://user-images.githubusercontent.com/8685709/134810994-aed76a41-8c1a-47f7-8bf9-5e2f83485549.png">

(After zoom )
<img width="304" alt="Zrzut ekranu 2021-09-26 o 15 57 56" src="https://user-images.githubusercontent.com/8685709/134810995-e503f9d2-6512-4952-84b4-d58e58fc6431.png">

I'm not sure if it's a bug or maybe there is a prop which can I use to fix it. 

Thanks for advance :)

**Comment by lafiosca** [comment]
I would probably not expect this to work with the current library as-is, but there may be some hacky workaround. Could you share some more detail on how the zoom works?

**Comment by tommyy911** [comment]
Thanks for the response :) 
Sure, zoom is the simple parent with animated styles
`  const style = useAnimatedStyle(() => {
        return {
            transform: [
                { scale: zoomLevel.value },
                { scale: zoomLevel!value },
                { translateX: offsetX.value },
                { translateY: offsetY.value },
            ],
        };
    });
`
as a child I have a few DragViews. 
I was hoping to find some property which allow to recalculate a position of DragViews after trigger Zoom function in the parent.

**Comment by TarikHuber** [comment]
@tommyy911 could you pls explain a little bit more about how you managed to solve this issue? We have exactly the same one.
