### ISSUE TITLE
Wrong position draggable item when orientation was changed

### ISSUE THREAD

**Issue by xdarkleonx** [nuclearpasta/react-native-drax#115]
```
<DraxProvider>
   <View style={styles.container}>
        <DraxList
          data={alphaData}
          renderItemContent={({ item }) => renderItem(item)}
          onItemReorder={({ fromIndex, toIndex }) => reorderItems(fromIndex, toIndex)}
          keyExtractor={(item) => item}
        />
      </View>
  </DraxProvider>
```

I am using DraxList. When I change orientation (landscape/portrait), draggable item has a wrong behavior. He is jumping ups outside of screen. I think this is happens because position is recalculates wrong when orientation changes.

**Comment by lafiosca** [comment]
I don't know how soon I'll be able to look into this, but to gather more information first...

As per your comments in #112, this has happened for you in Android API 29 emulator? Have you experienced it in any other environments as well? And does https://github.com/nuclearpasta/react-native-drax-example have this same buggy behavior for you? Thank you.

**Comment by xdarkleonx** [comment]
[Video demonstration.](https://drive.google.com/file/d/1kXSyYafsIGp9aAmYs3b75v-j_tLAQPy_/view?usp=sharing)
Tested on android emulator API 29 and on device - Honor 8S. In both cases there is a bug.

**Comment by lafiosca** [comment]
I apologize, I’m really not trying to make this difficult; but if the example code is working for you but your own code is not, I think we will need to see a minimally reproduced example of the bad behavior to be able to debug.

**Comment by xdarkleonx** [comment]
I was trying reproduce mistake [(here code),](https://snack.expo.dev/@darkleon/draxlist) but I could not. I can't understand why in my project draxlist work wrong.

**Comment by lafiosca** [comment]
Is it possible that in your actual app the DraxProvider is nestled underneath something that moves it around? You can think of the provider as an invisible view rectangle that determines the canvas for dragging. As such it should be put as high up in your hierarchy as possible, preferably in a spot where it won’t be changing layout position.

**Comment by xdarkleonx** [comment]
Ok, thanks. It looks like this is a problem on my side, so I am closing the issue.

**Comment by lafiosca** [comment]
Good luck. If you learn anything illuminating or discover a bug, please feel free to share here or reopen this issue.
