### ISSUE TITLE
Drag Drop between 2 DraxList

### ISSUE THREAD

**Issue by fukuli053** [nuclearpasta/react-native-drax#120]
How can I move items from DraxList to another DraxList? I tried it with DraxView, it was successful but I couldn't reorder when I was moving to another DraxList. Just added. When I drag it to another DraxList I also need to be able to specify its position.

**Comment by alexkendall** [comment]
Great question, wondering the same.

**Comment by lafiosca** [comment]
Sorry y’all, there’s not currently a built-in way to do this. It’s a feature request in the backlog. Please see #71 and #75. I’m going to close this issue as a duplicate.
