### ISSUE TITLE
question: for re-ordering example, is it possible to make it to be 2 columns?

### ISSUE THREAD

**Issue by JonathanSum** [nuclearpasta/react-native-drax#122]
![image](https://user-images.githubusercontent.com/21982975/144472765-b0a9b661-3e4e-458a-ab31-244fefe4168c.png)
question: for re-ordering example, is it possible to make it to be 2 columns?
Thank you for answering

**Comment by lafiosca** [comment]
Hi @JonathanSum. It depends what you mean, but essentially: not quite yet, at least not smoothly. If you want a single multi-column list, there are several issues and PRs related to that such as #14 #67 #99 and the feature hasn't been completed yet. If you mean you want two separate DraxLists that you can drag between, that is also not supported yet but will hopefully be added at some point (see #71 #75 etc). Folks have invented some workarounds and experiments for these things which you may be able to find by digging around those links.

**Comment by lafiosca** [comment]
I'm going to close this issue for now, but if I haven't actually answered the question, please let me know and we can reopen it.

**Comment by JonathanSum** [comment]
![image](https://user-images.githubusercontent.com/21982975/144644704-ceedc5d2-145e-4204-8273-62eb40001a9f.png)
Hi. Thank you for answering. It is something similar to this.

**Comment by lafiosca** [comment]
So this just appears to be a multi-column list. You can use the `numColumns` prop that a vanilla `FlatList` has, but as per #14 there will be some cosmetic issues when dragging items around.
