### ISSUE TITLE
Cannot read properties of undefined (reading 'remove')

### ISSUE THREAD

**Issue by xclidongbo** [nuclearpasta/react-native-drax#146]
Cannot read properties of undefined (reading 'remove')

**Comment by lafiosca** [comment]
Which versions of React Native and Drax are you using? This seems related to the breaking changes in 0.10.0. From the README:

> Note: as of version 0.10.0, React Native 0.65 or higher is required. For RN 0.62-0.64 projects, you may be able to use 0.9.3, but it will no longer be supported. For RN 0.61 projects, you may be able to use 0.6.0, but it will no longer be supported.

**Comment by lafiosca** [comment]
Closing this for lack of response. Feel free to reopen.
