### ISSUE TITLE
Is there a way to make it so when you click on a draggable object it also changes the objects style?

### ISSUE THREAD

**Issue by AlexanderNocelotl** [nuclearpasta/react-native-drax#173]
I want to create a object that when clicked on, it changes color, while also being draggable.

**Comment by lafiosca** [comment]
Check out the various DraxViewStyleProps in https://github.com/nuclearpasta/react-native-drax/blob/main/src/types.ts as used in the example here: https://github.com/nuclearpasta/react-native-drax-example/blob/main/src/screens/ColorDragDrop.tsx
