### ISSUE TITLE
Bug: DraxList doesn't handle dragging out of the list and back in

### ISSUE THREAD

**Issue by special-character** [nuclearpasta/react-native-drax#27]
I noticed that dragging an item outside the DragList and back into the list has odd behavior. Here is a screen cap.

![DraxList Exit Bug](https://user-images.githubusercontent.com/5407471/84078578-060a2600-a98e-11ea-8e46-1572ac87dd99.gif)

In the example, I drag an item over the tab bar which is outside the `DraxProvider`. I confirmed that pulling the `DraxProvider` up to the root of the app fixes the issue but I can't do that for my current use case. 

It seems that it starts behaving as expected only after I drag it back to it's original position. I am guessing that the `onMonitorDragExit` is called when it exits but it doesn't call `onMonitorDragEnter` and set handlers back up accordingly. I will take a crack at making a PR for this!

**Comment by special-character** [comment]
I tried taking a stab at this and it and haven't figured out quite how to do it yet. When the item is dragged outside the list, `handleDragEnd` clears out the `shifts` array (which is good b/c we want the item to go back to the original location if it is dropped outside the list). The issue is trying to get the drag state to be initialized and start back up again from where the item was dragged back into the list from.

My initial try was like this:

```
const onMonitorDragEnter = useCallback(
	({ dragged }: DraxMonitorEventData) => {
                 // Set the dragged item and start the scroll again
		setDraggedItem(dragged.payload.index)
		scrollStateRef.current = AutoScrollDirection.Back;
		startScroll()
	},
	[handleInternalDragEnd],
);
```

This didn't seem to change the behavior at all. I think there is some state that I am not setting correctly.

**Comment by lafiosca** [comment]
Thanks for bringing this up and taking a crack at it. I will try to take a look at it as soon as I am able, and you're welcome to continue digging if you feel up to it. I don't recall it behaving this way previously, so I wonder if I introduced a mistake at some point. Off the top of my head, I am also curious if this has anything to do with the fact that you're dragging outside of the DraxProvider (which is stuck within the content of the navigation tab screen), although I wouldn't expect that to cause a problem.

**Comment by lafiosca** [comment]
I'm sorry, I just caught your notes about the DraxProvider at the bottom of the initial post! I'm set up and about to look into this for a bit.

**Comment by lafiosca** [comment]
Refreshed my memory of the `DraxList` logic on stream tonight, and determined this was a missing line in the reset logic. For each list item, we track an `Animated.Value` for the shift translation, but we also track a regular `number` for the target value of that animation so that we do not double-animate. The reset function was not resetting the target values, only the animated.

PR #33 addresses the bug, and I'll cut a point release immediately.
