### ISSUE TITLE
Feature Request: Allow specifying custom Animated function for moving/snapping dropped items

### ISSUE THREAD

**Issue by special-character** [nuclearpasta/react-native-drax#28]
It would be great to be able to specify the animation for a dropped item. Right now it is this timing function: 

https://github.com/nuclearpasta/react-native-drax/blob/master/src/hooks/useDraxRegistry.ts#L493

I confirmed that I could manually change that to the spring function and it worked as expected. I could probably take a look at doing this. It should be a fairly straightforward option to configure.

**Comment by lafiosca** [comment]
I poked my head into the code for a moment and whipped up something, but I am on a new computer that I have not yet configured to run React Native apps. Could you take a look and see if this works for you? https://github.com/nuclearpasta/react-native-drax/tree/snapback-animation

The idea is that you pass a `snapbackAnimator` prop to the `DraxView` which could look something like:
```
  snapbackAnimator={({ hoverPosition, toValue }) => Animated.spring(hoverPosition, { toValue })}
```

This should also interoperate with the existing features for `snapbackDuration`, `snapbackDelay`, and the snapback target overrides.

One thing that occurs to me though: if you're trying to modify this behavior with a `DraxList`, we need a way to accept those props and pass them through to the underlying `renderItem` `DraxView`s.

**Comment by lafiosca** [comment]
Created PR #31 for easier comparison of changes
