### ISSUE TITLE
ability to use own transforms in `hoverDraggingStyle`

### ISSUE THREAD

**Issue by chrisdrackett** [nuclearpasta/react-native-drax#35]
right now any `transform` added to `hoverDraggingStyle` is overwritten here: https://github.com/nuclearpasta/react-native-drax/blob/97d3cf90d1e0934c3956005e01c1273d114f5c4f/src/DraxView.tsx#L229

**Comment by lafiosca** [comment]
Do you imagine that you'd want the hover translation to be applied on top of your transform, or would it be preferable to be able to completely override it, or are both necessary?

**Comment by chrisdrackett** [comment]
for my purposes I just want to apply it on top. Basically I would just be using a scale and/or a rotate. I can't think of a use case where I would want to adjust the translation (apart from *maybe* adding an offset, but that would be something different I think)

**Comment by lafiosca** [comment]
Thanks, I will take a crack at this shortly.

**Comment by lafiosca** [comment]
Ran long working on other issues tonight, hope to take a look at this this weekend. Sorry for the delay.

**Comment by lafiosca** [comment]
Am I understanding correctly that when I add this feature, it will conflict with #36 ? (Particularly if I apply the feature to all hover styles, not just hoverDraggingStyle.)

**Comment by chrisdrackett** [comment]
Yes, the PR is just trying to better document the current state so others don’t get confused like I did :)

**Comment by lafiosca** [comment]
All right. I think I'll hold off and not merge it then because I hope to address the other issue soonish. At that point, I'll close this PR. 😸

**Comment by lafiosca** [comment]
A million apologies for the massive delay @chrisdrackett but this will be in the next release
