### ISSUE TITLE
Scroll is not working 

### ISSUE THREAD

**Issue by DevopsStudioGraphene** [nuclearpasta/react-native-drax#43]
I have added one scroll view inside <DraxProvider> and on dragging scroll is not happening

**Comment by lafiosca** [comment]
I don't understand what you mean. Could you provide more information and background on what you're doing? A code sample might help.

**Comment by lafiosca** [comment]
@DevopsStudioGraphene Pinging you again on this. If you can provide more information, I will try to help. I'll leave the issue open for now.

**Comment by DevopsStudioGraphene** [comment]
@lafiosca - really sorry for the late response here. I had been away for the full week. Please feel free to close this issue, since I found that the real issue was within my piece of code. Apologies for any confusion created here.

**Comment by lafiosca** [comment]
Thank you for the update. No worries!

**Comment by rjuevesano** [comment]
Can you help me how to use this `DraxScrollView`?

I'm trying to move an item from A to B and B to A.

So here's my code

```
<DraxProvider>
          <DraxScrollView>
                <DraxView
                  renderContent={({ viewState }) => {
                    const receivingDrag = viewState && viewState.receivingDrag;
                    const payload = receivingDrag && receivingDrag.payload;
                    return "some_content_here";
                  }}
                  onReceiveDragDrop={({ dragged: { payload } }) => {
                    console.log(`received ${payload}`);
                  }}
                />
                <DraxView
                  renderContent={({ viewState }) => {
                    const receivingDrag = viewState && viewState.receivingDrag;
                    const payload = receivingDrag && receivingDrag.payload;
                    return "some_content_here";
                  }}
                  onReceiveDragDrop={({ dragged: { payload } }) => {
                    console.log(`received ${payload}`);
                  }}
                />
          </DraxScrollView>
        </DraxProvider>
```
