### ISSUE TITLE
Why DraxView is not working as it should be with ScrollView?

### ISSUE THREAD

**Issue by anupkmaharjan** [nuclearpasta/react-native-drax#51]
I am using the <DraxView /> inside the <ScrollView /> when the <DraxView /> is pressed it pops out from the original position and works smooth for all those which are visible, once we scroll it horizontally and pressed it, it do not pop out from position where it is pressed but comes out from the position where the <DraxView /> is originally placed while loading.
![image](https://user-images.githubusercontent.com/5188111/87768146-6f0d7500-c83b-11ea-9144-4cf94ae45cce.png)

![image](https://user-images.githubusercontent.com/5188111/87768226-8ba9ad00-c83b-11ea-8483-3d1c21a509b5.png)

![image](https://user-images.githubusercontent.com/5188111/87768301-a4b25e00-c83b-11ea-8d44-b13a47d6f663.png)

**Comment by anupkmaharjan** [comment]
I found the DraxScrollView and used it instead of ScrollView.

**Comment by lafiosca** [comment]
I’m sorry for not yet having more thorough documentation @anupkmaharjan
