### ISSUE TITLE
RN 0.62.x: <DraxList> triggers warning

### ISSUE THREAD

**Issue by alex-golubtsov** [nuclearpasta/react-native-drax#54]
Having `react-native@0.62.x`, `<DraxList>` triggers following warning (here is [an example](https://snack.expo.io/@lafiosca/react-native-drax---basic-reorderable-list?platform=ios)):
```
Calling `getNode()` on the ref of an Animated component is no longer necessary...
```

Probably because of [this line](https://github.com/nuclearpasta/react-native-drax/blob/prerelease/src/DraxView.tsx#L635).
Seems like the fix would be as simple as removing `.getNode()` call

**Comment by lafiosca** [comment]
Thanks for bringing this up @alex-golubtsov ... I have not yet upgraded to 0.62 in the app that we originally built this library for, and I'm uncertain if this would be a breaking change for pre-0.62 apps. It will need to be tested.

**Comment by lafiosca** [comment]
Here is the relevant change which occurred in 0.62: https://github.com/facebook/react-native/commit/66e72bb4e00aafbcb9f450ed5db261d98f99f82a

**Comment by lafiosca** [comment]
First thought on this is that I would need to support some option for accessing the old way in pre-0.62 apps but default to the new way.

**Comment by lafiosca** [comment]
I'm in the process of uploading my own mobile app from RN 0.61 to 0.63 now, and as a result I will definitely be giving this issue attention soon. Likely we will make a breaking change to the library and update the README accordingly.

**Comment by lafiosca** [comment]
Version 0.7.0 has been published with this issue fixed. Only RN 0.62+ will be supported going forward. However please note that you may still see warnings regarding `useNativeDriver` until #57 is addressed. Thank you.
