### ISSUE TITLE
Expose DraxView longPressDelay in DraxList props

### ISSUE THREAD

**Issue by lafiosca** [nuclearpasta/react-native-drax#59]
Currently the longPressDelay for DraxView items nested in a DraxList is hardcoded to 250ms. Let's expose this prop to make it configurable.

**Comment by sturdynut** [comment]
@lafiosca -  I am loving this library! I really wanted to specify a longPressDelay of 0 for the DraxList for my app, so I forked it and added this in.  I'm going to PR it in the case you guys want to bring these changes in.

**Comment by lafiosca** [comment]
Thanks for the kind words and PR! It's been released in 0.8.2.

Note for your future reference that it was already possible to do this with a `viewPropsExtractor` (see #92 and #108), but I still think this is a common and simple enough property that it makes sense to expose it directly like this as well.
