### ISSUE TITLE
Changing length of DraxList data array causes app to crash

### ISSUE THREAD

**Issue by lafiosca** [nuclearpasta/react-native-drax#6]
When a DraxList is reused with a new data array of a shorter length, the cached reorder logic causes it to send undefined items to the underlying FlatList, which can crash the app when the keyExtractor or renderItem methods try to access fields of the undefined item.

**Comment by lafiosca** [comment]
![image](https://user-images.githubusercontent.com/9442662/71676179-8e382f80-2d4d-11ea-8114-f394eaad2d30.png)

`reorderedData` is what's fed to the underlying `FlatList`. It seems like there is a moment where `data` has changed, but `originalIndexes` has not yet been updated, and so `reorderedData` contains `undefined` items. Ideally this would not happen, and when the new `data` came in, we'd simultaneously update `originalIndexes` and have the new `reorderedData`. I'm not sure if this is possible with our approach. I tested, and removing the `useMemo` did not accomplish/fix this.

I see several possible approaches here, all in the `useMemo` call for `reorderedData`:

1. Filter out undefined items from the map
2. Check if `data.length` !== `originalIndexes.length` and:
2a. Return `null`
2b. Return `data`

In all of these approaches, if data changes to a new array with the same length, and if there is currently a cached reorder to the list, then there will/may be an instant when the new data is rendered with the cached reorder.

In approach 1, if the data length changes, there will/may be an instant when the new data is rendered with the partially applied cached reorder.

In approach 2a, if the data length changes, there will/may be an instant when no data is rendered.

In approach 2b, if the data length changes, there will/may be an instant where the raw underlying data is rendered, quickly followed by the same data presented in the same order as the `originalIndexes` array is reset.

I think the decision is fairly arbitrary for now, so try out 2b.

**Comment by lafiosca** [comment]
2b worked to avoid the crash, but while testing I noticed a related crash. When increasing the number of items in the list, there is a moment before the `shiftsRef` array has been expanded, during which `getShiftTransform` can access beyond the end and crash. Tweaking that code to default to 0:

```
			const shift = shiftsRef.current[index]?.animatedValue ?? 0;
```

**Comment by debianw** [comment]
This crash is still happening when data length changes

**Comment by lafiosca** [comment]
@debianw Could I get you to provide a minimal reproduction of this crash in a Snack? It would help me out a lot with my limited availability.

**Comment by debianw** [comment]
@lafiosca here I posted a demo todo App that you can use to reproduce it https://github.com/nuclearpasta/react-native-drax/issues/103
