### ISSUE TITLE
Unable to set draggable={false} on items when using DraxList

### ISSUE THREAD

**Issue by afgarcia86** [nuclearpasta/react-native-drax#62]
I see I can use reorderable={true/false} however that doesn't stop the person from being able to attempt to drag an item. Wondering if I am missing something and there is a away to pass the draggableProp in.

**Comment by lafiosca** [comment]
Hmm, I can’t look now, but off the top of my head this is not currently supported. I think it is a reasonable feature request.

**Comment by afgarcia86** [comment]
I believe this would do it https://github.com/nuclearpasta/react-native-drax/pull/64
