### ISSUE TITLE
DraxList disable a x-axis

### ISSUE THREAD

**Issue by vomchik** [nuclearpasta/react-native-drax#65]
It's possible to disable the x-axis on a drag?

**Comment by lafiosca** [comment]
Not currently, no. That would be a new feature. Could you give me a little more info about the use case?

**Comment by vomchik** [comment]
@lafiosca as you can see a draggable element can be moved in x and y direction. i want to allow only the y-axis.
![CleanShot 2020-11-11 at 13 54 40](https://user-images.githubusercontent.com/732085/98809002-a2e15b80-2425-11eb-9b81-880646a52cbb.gif)

**Comment by lafiosca** [comment]
Well I meant more about the “why” and “when” it would be used? Are you envisioning this specifically within DraxLists or as a feature for all DraxViews?

**Comment by vomchik** [comment]
In my case, it only for DraxLists. i guess this is standard behavior for a sortable list, no?)

**Comment by lafiosca** [comment]
Quoting myself from #68:

> I'm imagining a new `DraxList` prop named `lockDragAxis` which causes the list items to only be draggable within the orientation axis of the list. And perhaps `DraxView` props named `lockDragXAxis` and `lockDragYAxis`, which the `DraxList` can use to implement that. I think the `DraxView` can probably use these props cosmetically rather than modifying the values in the provider's drag handling; it will just modify the hover transform styling to ignore one or the other value. I will work up a separate PR.

**Comment by lafiosca** [comment]
Technically I guess these should be `lockHoverAxis` since it's just a cosmetic change I'm suggesting, not a drag/gesture manipulation.

**Comment by lafiosca** [comment]
Digging into the code, I guess I probably will need to modify the gesture values in some deeper sense. This could be accomplished in various ways:

- Explicitly add axis locks to the Drax protocol and account for them in gesture handling
- Zero out the gesture event's x or y in the `DraxView` before passing it to the `handleGestureEvent` handler
- Add an parameter to the `handleGestureEvent` to accept options like axis locks, which again the `DraxView` specifies at the time of passing to that handler

I will think about the pros and cons and pick one of these approaches. Any of them should work fine for this specific issue, but I'm trying to maintain flexibility and power for potential future requests.

**Comment by lafiosca** [comment]
After some experimentation, I decided it made more sense to actually lock the drag position in the system. This makes the reorderable lists behave more sensibly in certain situations, such as for a horizontal list which does not fill the entire height of the screen. PR coming up shortly.

**Comment by lafiosca** [comment]
I will publish a new release with this hopefully later today
