### ISSUE TITLE
DraxList pure performance for Android

### ISSUE THREAD

**Issue by vomchik** [nuclearpasta/react-native-drax#66]
As you can see on record UI is pretty slow on Android, but on iOS it works much better.
Android:
![CleanShot 2020-11-11 at 14 01 21](https://user-images.githubusercontent.com/732085/98847731-62033a00-2459-11eb-8bfb-7d4025c02c23.gif)
iOS:
![CleanShot 2020-11-11 at 13 54 40](https://user-images.githubusercontent.com/732085/98847932-a8589900-2459-11eb-85c3-b15abe1b1b98.gif)

**Comment by lafiosca** [comment]
I find that in general, but especially with this library and example project, the performance in the Android Emulator is much worse than testing on a physical device. Even the old Samsung Galaxy S7 Edge that I use for development looks a lot smoother than this.

All that said, I remain open to input from people who have more Android experience and see ways of improving the performance of this library. Considering though that this library provides no native code of its own, it is reliant on the performance of react-native-gesture-handler and animated views, and there may be limited options.

I will leave this issue open in case anyone has additional input.

**Comment by adrian19hub** [comment]
For me its slow on a real davice.

**Comment by lafiosca** [comment]
Unfortunately this library is probably quite out of date by now, as no one has been actively maintaining or improving it.
