### ISSUE TITLE
DraxList not working on iOS

### ISSUE THREAD

**Issue by likon416** [nuclearpasta/react-native-drax#95]
Hello. 

I'm running react-native-drax-example on iOS simulator (v14.4) and I can't drag & drop list item, it's dragging me the whole list. 
Could you please look into it?

Thanks.

**Comment by likon416** [comment]
HI @lafiosca . 

Thank you for replaying. It was iPhone 11 simulator with iOS 14.4. Currently I can't even run the app. Attaching the screenshot. 

Will try to run it on Android. If I will fix iOS then will replay more but overall I took newest repo and followed the steps described there. 

Do you know maybe what can be the problem so I can't run the app on iOS?

<img width="475" alt="Screenshot 2021-05-04 at 08 37 21" src="https://user-images.githubusercontent.com/83599161/116973236-1fa61180-acb4-11eb-9ed2-ff86159fcc48.png">

**Comment by likon416** [comment]
Thanks @lafiosca 

I finally fixed my simulator and tried pressing long and it works fine. Sorry for the trouble. 

Plugin is really awesome btw. Best on the market :)

**Comment by lafiosca** [comment]
Thank you, glad it worked out for you!
